spring:
  application:
    name: ordering
  cloud:
    circuitbreaker:
      http-services:
        enabled: false
  flyway:
    enabled: false
  http:
    clients:
      imperative:
        factory: http_components
    serviceclient:
      product-catalog:
        connect-timeout: 2s
        read-timeout: 5s
      rapidex:
        connect-timeout: 3s
        read-timeout: 7s
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    open-in-view: false
    show-sql: false
  web:
    locale-resolver: fixed
    locale: en_US

algashop:
  integrations:
    product-catalog:
      provider: PRODUCT_CATALOG
    shipping:
      provider: RAPIDEX