logging:
  level:
    net.ttddyy.dsproxy.listener: DEBUG
    org.apache.hc.client5.http: DEBUG

spring:
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password: algashop
      database: 1
      timeout: 600
  datasource:
    url: jdbc:postgresql://localhost:5432/ordering
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  http:
    clients:
      imperative:
        factory: http_components
    serviceclient:
      product-catalog:
        base-url: http://localhost:8083
      rapidex:
        base-url: http://localhost:8787
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081

algashop:
  integrations:
    product-catalog:
      provider: PRODUCT_CATALOG
    shipping:
      provider: RAPIDEX