CREATE TABLE public.customer
(
    id                              UUID NOT NULL,
    first_name                      VARCHAR(255),
    last_name                       VARCHAR(255),
    birth_date                      date,
    email                           VARCHAR(255),
    phone                           VARCHAR(255),
    document                        VARCHAR(255),
    promotion_notifications_allowed BOOLEAN,
    archived                        BOOLEAN,
    registered_at                   TIMESTAMP WITHOUT TIME ZONE,
    archived_at                     TIMESTAMP WITHOUT TIME ZONE,
    loyalty_points                  INTEGER,
    created_by                      UUID,
    created_at                      TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by                UUID,
    last_modified_at                TIMESTAMP WITHOUT TIME ZONE,
    version                         BIGINT,
    address_street                  VARCHAR(255),
    address_number                  VARCHAR(255),
    address_complement              VARCHAR(255),
    address_neighborhood            VARCHAR(255),
    address_city                    VARCHAR(255),
    address_state                   VARCHAR(255),
    address_zip_code                VARCHAR(255),
    CONSTRAINT uk_customer_email UNIQUE (email),
    CONSTRAINT pk_customer PRIMARY KEY (id)
);
